openapi: 3.0.0
info:
  title: Pongmasters API
  description: The REST-ful API to interact with the Pongmasters gateway.
  version: 1.0.0
servers:
  - url: /api/v1
    description: Main API server
paths:
  /users:
    post:
      summary: User registration
      description: Register a new user in the system by providing email, password, and display name.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCredentials"
          application/xml:
            schema:
              $ref: "#/components/schemas/UserCredentials"
      responses:
        "200":
          description: Returns the user ID upon successful registration.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user_id"
            application/xml:
              schema:
                $ref: "#/components/schemas/user_id"
        "400":
          description: Bad request due to invalid input data.
        "409":
          description: Conflict, e.g., user with this email already exists.
    get:
      summary: Get a list of users
      description: Retrieve a paginated list of users.
      parameters:
        - name: page
          in: query
          description: The page number of the results to retrieve.
          schema:
            type: integer
            format: int32
            minimum: 1
        - name: results_per_page
          in: query
          description: The number of users to display per page.
          schema:
            type: integer
            format: int32
            minimum: 1
      security:
        - jwtAuth: []
      responses:
        "200":
          description: Returns an array of User objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
            application/xml:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "401":
          description: Unauthorized access, JWT token is missing or invalid.
  /users/{user_id}:
    get:
      summary: Get user data by user_id
      description: Retrieve detailed information of a specific user using their unique user_id.
      parameters:
        - name: user_id
          in: path
          required: true
          description: The unique identifier of the user to retrieve.
          schema:
            $ref: "#/components/schemas/user_id"
      security:
        - jwtAuth: []
      responses:
        "200":
          description: Returns the User object of the specified user.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
            application/xml:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: User not found.
        "401":
          description: Unauthorized access, JWT token is missing or invalid.
    put:
      summary: Update user credentials
      description: Update the email, password, or display name of a user using their user_id.
      parameters:
        - name: user_id
          in: path
          required: true
          description: The unique identifier of the user to update.
          schema:
            $ref: "#/components/schemas/user_id"
      security:
        - jwtAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCredentials"
          application/xml:
            schema:
              $ref: "#/components/schemas/UserCredentials"
      responses:
        "200":
          description: User data updated successfully.
        "400":
          description: Bad request due to invalid input data.
        "404":
          description: User not found.
        "401":
          description: Unauthorized access, JWT token is missing or invalid.
    delete:
      summary: Delete a user account
      description: Permanently delete a user account by their user_id.
      parameters:
        - name: user_id
          in: path
          required: true
          description: The unique identifier of the user to delete.
          schema:
            $ref: "#/components/schemas/user_id"
      security:
        - jwtAuth: []
      responses:
        "204":
          description: User account deleted successfully.
        "404":
          description: User not found.
        "401":
          description: Unauthorized access, JWT token is missing or invalid.
  
  /sessions:
    get:
      summary: Get login status of all users
      description: Retrieve the login status of all users.
      security:
        - jwtAuth: []
      responses:
        "200":
          description: Returns a map of user_ids and their respective statuses.
          content:
            application/json:
              schema:
                type: object
                description: a map of user_ids and their respective status.
                additionalProperties:
                  $ref: "#/components/schemas/user_status"
            application/xml:
              schema:
                type: object
                description: a map of user IDs and their respective status.
                additionalProperties:
                  $ref: "#/components/schemas/user_status"
        "401":
          description: Unauthorized access, JWT token is missing or invalid.
    delete:
      summary: Disconnect all users
      description: Logs out all users from the system.
      security:
        - jwtAuth: []
      responses:
        "204":
          description: All users successfully logged out.
        "401":
          description: Unauthorized access, JWT token is missing or invalid.
  /sessions/{user_id}:
    post:
      summary: User login
      description: Authenticate the user and return a JWT token for session management.
      parameters:
        - name: user_id
          in: path
          required: true
          description: The unique identifier of the user attempting to log in.
          schema:
            $ref: "#/components/schemas/user_id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user_psw"
          application/xml:
            schema:
              $ref: "#/components/schemas/user_psw"
      responses:
        "200":
          description: Returns a JWT token upon successful authentication.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/jwt_token"
            application/xml:
              schema:
                $ref: "#/components/schemas/jwt_token"
        "400":
          description: Bad request due to invalid credentials.
        "404":
          description: User not found.
    get:
      summary: Get user login status
      description: Check if a user is currently logged in and return their status.
      parameters:
        - name: user_id
          in: path
          required: true
          description: The unique identifier of the user to check.
          schema:
            $ref: "#/components/schemas/user_id"
      security:
        - jwtAuth: []
      responses:
        "200":
          description: Returns the login status of the user.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user_status"
            application/xml:
              schema:
                $ref: "#/components/schemas/user_status"
        "404":
          description: User not found.
        "401":
          description: Unauthorized access, JWT token is missing or invalid.
    delete:
      summary: User logout
      description: Logs out a specific user from the system.
      parameters:
        - name: user_id
          in: path
          required: true
          description: The unique identifier of the user to log out.
          schema:
            $ref: "#/components/schemas/user_id"
      security:
        - jwtAuth: []
      responses:
        "204":
          description: User successfully logged out.
        "404":
          description: User not found.
        "401":
          description: Unauthorized access, JWT token is missing or invalid.

  /matches:
    post:
      summary: Start a new match
      description: Initialize a new Pong match by providing the match settings.
      security:
        - jwtAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MatchSettings"
          application/xml:
            schema:
              $ref: "#/components/schemas/MatchSettings"
      responses:
        "200":
          description: Returns a Match object, including the WebSocket URL for real-time communication during the game.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Match"
            application/xml:
              schema:
                $ref: "#/components/schemas/Match"
        "400":
          description: Bad request due to invalid match settings.
        "401":
          description: Unauthorized access, JWT token is missing or invalid.
        "409":
          description: Conflict, e.g., match already in progress.
    delete:
      summary: Interrupt all ongoing matches
      description: Terminate all currently active matches and clear session data.
      security:
        - jwtAuth: []
      responses:
        "204":
          description: All matches interrupted successfully.
        "401":
          description: Unauthorized access, JWT token is missing or invalid.
  /matches/{match_id}:
    post:
      summary: Join an ongoing match
      description: Allows a user to join an ongoing match by providing the match ID.
      parameters:
        - name: match_id
          in: path
          required: true
          description: The unique identifier of the match to join.
          schema:
            $ref: "#/components/schemas/match_id"
      security:
        - jwtAuth: []
      responses:
        "200":
          description: Successfully joined the match.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Match"
            application/xml:
              schema:
                $ref: "#/components/schemas/Match"
        "404":
          description: Match not found.
        "401":
          description: Unauthorized access, JWT token is missing or invalid.
    get:
      summary: Get info on an ongoing match
      description: Retrieve details about a specific ongoing match using its ID.
      parameters:
        - name: match_id
          in: path
          required: true
          description: The unique identifier of the match to retrieve information for.
          schema:
            $ref: "#/components/schemas/match_id"
      responses:
        "200":
          description: Returns match information.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Match"
            application/xml:
              schema:
                $ref: "#/components/schemas/Match"
        "404":
          description: Match not found.
        "401":
          description: Unauthorized access, JWT token is missing or invalid.
    delete:
      summary: Abandon the current match
      description: Exit and terminate the ongoing match.
      parameters:
        - name: match_id
          in: path
          required: true
          description: The unique identifier of the match to abandon.
          schema:
            $ref: "#/components/schemas/match_id"
      security:
        - jwtAuth: []
      responses:
        "204":
          description: Match abandoned successfully.
        "404":
          description: Match not found.
        "401":
          description: Unauthorized access, JWT token is missing or invalid.

components:
  schemas:

    user_id:
      type: string
      description: Unique identifier for the user (or AI bot) (UUID format or similar).
    user_psw:
      type: string
      description: The user's password (plain-text) for authentication.
    user_email:
      type: string
      description: The user's email address, used for login and notifications.
    user_display_name:
      type: string
      description: The display name of the user, visible to other players during gameplay.
    user_status:
      type: string
      enum: [online, offline]
      example: online
      description: The current status of the user (online or offline).
    jwt_token:
      type: string
      description: JWT token for session management.
    websocket_url:
      type: string
      description: The WebSocket URL for real-time interaction during the match. Used by clients to establish connections and interact with the game in real-time.
    match_id:
      type: string
      description: Unique identifier for the match (UUID format or similar).
    match_status:
      type: string
      enum: [ongoing, completed, interrupted]
      description: Current status of the match.
    match_ball_speed:
      type: integer
      format: int32
      minimum: 1
      maximum: 100
      description: Defines the speed of the ball in the match.
    match_max_duration:
      type: integer
      format: int32
      minimum: 60
      maximum: 3600
      description: Maximum allowable duration (seconds) for the match.
    match_starting_health_points:
      type: integer
      format: int32
      minimum: 1
      maximum: 100
      description: Initial health or lives given to each player at the start of the match.
    player_health_points:
      type: integer
      format: int32
      minimum: 0
      maximum: 100
      description: The current health points of the player.

    UserCredentials:
      type: object
      description: Represents the credentials used for user registration or login.
      properties:
        email:
          $ref: "#/components/schemas/user_email"
        psw:
          $ref: "#/components/schemas/user_psw"
        display_name:
          $ref: "#/components/schemas/user_display_name"
      xml:
        name: UserCredentials

    User:
      type: object
      description: Represents a user (or an AI bot) in the Pongmasters system.
      properties:
        user_id:
          $ref: "#/components/schemas/user_id"
        email:
          $ref: "#/components/schemas/user_email"      
        display_name:
          $ref: "#/components/schemas/user_display_name"
        status:
          $ref: "#/components/schemas/user_status"
      required:
        - user_id
      xml:
        name: User
    
    MatchSettings:
      type: object
      description: Settings and configurations for the match, such as ball speed, match duration, and player health.
      properties:
        ball_speed:
          $ref: "#/components/schemas/match_ball_speed"
        max_duration:
          $ref: "#/components/schemas/match_max_duration"
        starting_health:
          $ref: "#/components/schemas/match_starting_health"
      xml:
        name: MatchSettings

    Match:
      type: object
      description: Represents a Pong match, including players information, settings, and WebSocket connection details.
      properties:
        match_id:
          $ref: "#/components/schemas/match_id"
        websocket_url:
          $ref: "#/components/schemas/websocket_url"
        players:
          type: array
          description: An array of the players in the match.
          items:
            $ref: "#/components/schemas/User"
        healths:
          type: object
          description: A map of user IDs to their respective health points in the match.
          additionalProperties:
            $ref: "#/components/schemas/player_health_points"
        status:
          $ref: "#/components/schemas/match_status"
        match_settings:
          $ref: "#/components/schemas/MatchSettings"
      required:
        - match_id
      xml:
        name: Match

  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT used for authorization. Send the token in the `Authorization` header with the format `Bearer {token}`.

security:
  - jwtAuth: []