bind: 0.0.0.0:50052
pid_file: /var/run/user.pid

logging:
  level:  info
  file:   /dev/stdout

credentials:
  keys:
    user: /etc/ssl/private/user.key
  certs:
    user:       /etc/ssl/certs/user.crt
    db_gateway:      /etc/ssl/certs/db_gateway.crt
    auth:       /etc/ssl/certs/auth.crt
    redis: /etc/ssl/certs/redis.crt

addresses:
  db_gateway:        uery.corenet:50052
  auth:         auth.corenet:50052
  redis:   redis:6379

display_name:
  min_length: 3
  max_length: 25
  charset:
    lowercase: "abcdefghijklmnopqrstuvwxyz"
    uppercase: "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    digits:    "0123456789"
    special:   "!@#$%&*-_=+,.<>?"
  banned_words_file: /etc/default_banned_display_name_words.txt

password:
  min_length: 8
  max_length: 64
  charset:
    lowercase:  "abcdefghijklmnopqrstuvwxyz"
    uppercase:  "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    digits:     "0123456789"
    special:    "!@#$%&*-_=+,.<>?"
  policy:
    min_uppercase:  1
    min_lowercase:  1
    min_digits:     1
    min_special:    0
  banned_passwords_file: /etc/default_banned_passwords.txt

avatar:
  max_size: 1048576
  max_dimensions:
    width:  512
    height: 512
  allowed_types:
    - image/jpeg
    - image/png
    - image/gif
    - image/bmp
    - image/webp
  default: /etc/default_avatar.jpg